public enum UnitType
{
    Unit_Hero = 0,
    Unit_HiredBodyguard = 1,
    Unit_Scapegoat = 2,
    Unit_Intern = 3,
    Unit_CanMaker = 4,
    Unit_Brat = 5,
    Unit_Courier = 6,
    Unit_LateRider = 7,
    Unit_BoneButcher = 8,
    Unit_ColdCarrier = 9,
    Unit_HydroGunner = 10,
    Unit_Firefighter = 11,
    Unit_GateGuard = 12,
    Unit_RiotGuard = 13,
    Unit_LongbowHunter = 14,
    Unit_Poacher = 15,
    Unit_Gardener = 16,
    Unit_Harvester = 17,
    Unit_Surgeon = 18,
    Unit_Nurse = 19,
    Unit_Sprinter = 20,
    Unit_JavelinThrower = 21,
}
